// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mulher_Presente.Data;

namespace Mulher_Presente.Migrations
{
    [DbContext(typeof(VitimaUserContext))]
    [Migration("20220104232935_Mulher-Presente")]
    partial class MulherPresente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mulher_Presente.Models.ParceirosUser", b =>
                {
                    b.Property<string>("ID_parceiro")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email_parceiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone_parceiro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_parceiro");

                    b.ToTable("ParceirosUser");
                });

            modelBuilder.Entity("Mulher_Presente.Models.VitimaUser", b =>
                {
                    b.Property<string>("ID_vitima")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParceirosUserID_parceiro")
                        .HasColumnType("int");

                    b.Property<string>("ParceirosUserID_parceiro1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Telefone")
                        .HasColumnType("int");

                    b.HasKey("ID_vitima");

                    b.HasIndex("ParceirosUserID_parceiro1");

                    b.ToTable("VitimaUser");
                });

            modelBuilder.Entity("Mulher_Presente.Models.VitimaUser", b =>
                {
                    b.HasOne("Mulher_Presente.Models.ParceirosUser", "ParceirosUser")
                        .WithMany()
                        .HasForeignKey("ParceirosUserID_parceiro1");

                    b.Navigation("ParceirosUser");
                });
#pragma warning restore 612, 618
        }
    }
}
